### ISSUE TITLE
待机功耗过高

### ISSUE THREAD

**Issue by u0076** [milkv-pioneer/issues#24]
现象描述：
整机待机功率过高，除掉外设部分，2042 待机功率仍过高。

问题原因：
暂未找到原因

处理方式：
在 EVB 上确认 2042的待机功耗

跟进人：林春志

**Comment by Chunzhi-Lin** [comment]
在X8 EVB上待机功耗68W左右

**Comment by u0076** [comment]
Milk-V Pioneer 整机待机功率 116W，外设包括显卡、网卡和 SSD。待机功耗应该和 EVB 相差不大。
